// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyTO1s5XzdmuFWT0npUEHHWVMAHF928o',
    appId: '1:856784098084:web:1d90eb4f4a3d2f86bb19b1',
    messagingSenderId: '856784098084',
    projectId: 'pelatihan-mobile-6c08f',
    authDomain: 'pelatihan-mobile-6c08f.firebaseapp.com',
    storageBucket: 'pelatihan-mobile-6c08f.firebasestorage.app',
    measurementId: 'G-LHGS67FTXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt673-Gswb97D1iqcSqlwSiuTQYJXEEvM',
    appId: '1:856784098084:android:110b96313b4ca72abb19b1',
    messagingSenderId: '856784098084',
    projectId: 'pelatihan-mobile-6c08f',
    storageBucket: 'pelatihan-mobile-6c08f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPaZ0pgV9lqQIVS8-f95A9hODo5EJEXA',
    appId: '1:856784098084:ios:5e14bcd971183af5bb19b1',
    messagingSenderId: '856784098084',
    projectId: 'pelatihan-mobile-6c08f',
    storageBucket: 'pelatihan-mobile-6c08f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPaZ0pgV9lqQIVS8-f95A9hODo5EJEXA',
    appId: '1:856784098084:ios:5e14bcd971183af5bb19b1',
    messagingSenderId: '856784098084',
    projectId: 'pelatihan-mobile-6c08f',
    storageBucket: 'pelatihan-mobile-6c08f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoyTO1s5XzdmuFWT0npUEHHWVMAHF928o',
    appId: '1:856784098084:web:1aea9fdcf4103dc7bb19b1',
    messagingSenderId: '856784098084',
    projectId: 'pelatihan-mobile-6c08f',
    authDomain: 'pelatihan-mobile-6c08f.firebaseapp.com',
    storageBucket: 'pelatihan-mobile-6c08f.firebasestorage.app',
    measurementId: 'G-GWE21MSYJG',
  );

}